module.exports = [
    "🦀 Crabs are decapods, meaning they have ten legs including one pair of pincers!",
    "🦀 There are over 6,793 species of crabs in oceans, freshwater, and on land!",
    "🦀 Crabs can regenerate lost legs and claws over several molting cycles!",
    "🦀 Their eyes are on movable stalks allowing 360-degree vision without moving!",
    "🦀 Crabs typically walk sideways due to how their legs are hinged!",
    "🦀 Some crabs like the Japanese spider crab can live up to 100 years!",
    "🦀 Female crabs can lay between 1,000 and 2,000 eggs at a time!",
    "🦀 A group of crabs is called a 'cast'!",
    "🦀 Crabs communicate by waving their claws during mating rituals!",
    "🦀 Soft shell crabs are just crabs that recently molted!",
    "🦀 Crabs can 'smell' prey by following chemical signals in water!",
    "🦀 Some crabs can solve mazes and remember solutions for weeks!",
    "🦀 The coconut crab is the largest land-living arthropod!",
    "🦀 Crabs have a hard outer shell called an exoskeleton!",
    "🦀 They molt their shells to grow larger in a process called molting!",
    "🦀 Crabs are omnivores and will eat plants, animals, and even other crabs!",
    "🦀 Their mouth is located on the underside of their head!",
    "🦀 Crabs use strong claws to crack open shells and manipulate food!",
    "🦀 Some species like porcelain crabs have only eight legs!",
    "🦀 Crabs can drum their claws on shells to signal danger!"
];
